services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
